import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import pokemonApi from "../services/pokemonApi";
import { Container } from "../styles/home";

export const getServerSideProps = async () => {
  let pokemons = await pokemonApi.getListPokemons();

  return {
    props: {
      pokemons,
    },
  };
};

export default function Home({ pokemons }) {
  return (
    <Container>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <hr />

      <main>
        {pokemons &&
          pokemons.results.map((pokemon) => (
            <div key={pokemon.name}>
              <h3>{pokemon.name}</h3>
            </div>
          ))}
      </main>
    </Container>
  );
}
